### ISSUE TITLE
希望支持印象笔记国内版

### ISSUE THREAD

**Issue by congcong0806** [prairie/Eemory#68]
希望支持印象笔记国内版，谢谢！
https://dev.yinxiang.com/

**Comment by liujienwei** [comment]
@congcong0806 谢谢关注Eemory，我们会尽快计划一个release来支持印象笔记。

Thanks,
Jianwei

**Comment by congcong0806** [comment]
嗯嗯，非常感谢！



只有努力过,才会有收获.--聪聪
 
发件人： Jianwei Liu
发送时间： 2015-06-09 15:06
收件人： prairie/Eemory
抄送： cc
主题： Re: [Eemory] 希望支持印象笔记国内版 (#68)
@congcong0806 谢谢关注Eemory，我们会尽快计划一个release来支持印象笔记。
Thanks,
Jianwei

**Comment by liujienwei** [comment]
close as we have done all the things.

**Comment by liujienwei** [comment]
@congcong0806 v1.1.1 是最新的支持印象笔记的版本，欢迎试用。

Thanks,
Eemory Team
