### ISSUE TITLE
折叠的文件内容不会保存

### ISSUE THREAD

**Issue by nmcoo** [prairie/Eemory#91]
文件这部分内容在IDE是折叠了的，保存就只存了这一行，没有保存折叠的内容
![image](https://cloud.githubusercontent.com/assets/3024785/20916307/0c88808a-bbc6-11e6-803a-59e701c4fc27.png)

**Comment by liujianuuei** [comment]
### 问题分析

这是一个**已知问题**。 README 的 [Limits](https://github.com/LTTPP/Eemory#limits) 已经包含了此项限制：

> Folded pieces of code or any other text are not supported to clip. 不支持剪裁折叠的代码或其它文本。

就具体原因来说，是因为 Eemory 的实现是基于 Eclipse 的编辑器，所有文本风格都是来自于 Eclipse 的编辑器，而 Eclipse 的编辑器不支持返回折叠的代码，所以可以认为是 Eclipse 的限制。

这也是可以理解的，在 Eclipse 的编辑器里，奉行*所见即所得*原则，编辑器不是真正的文件，它只是一种*显示*，所以当代码折叠以后，对*显示*来说，就相当于不存在。

### 解决方案

没有。

### 变通方案

使用 Eemory 剪裁之前，打开折叠的代码。换句话说，你只能剪裁你看到的。

**Comment by liujianuuei** [comment]
@congcong0806 请告知，是否解决你的问题，是否可以关闭这个 issue？

**Comment by nmcoo** [comment]
谢谢，明白了。可以关闭了哈！
